// GetEmployeeById
http://localhost:5000/api/employee/id/77932819

###
// GetEmployeesByJobTitle
http://localhost:5000/api/employee/assistant manager

###
// CheckClockIdExists
http://localhost:5000/api/employee/clock/297351
