name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore employee-management-backend.sln

    - name: Build
      run: dotnet build employee-management-backend.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test employee-management-backend.sln --configuration Release --no-build --verbosity normal
